name: Unit Tests Coverage
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Start wp-env
        uses: godaddy-wordpress/setup-wp-env@v1
        with:
          core: "WordPress/WordPress"
          phpVersion: "8.1"
          plugins: '["https://wordpress.org/plugins/files/2024/02/28_22-03-24_serve-static.zip"]'
      - name: Checkout
        uses: actions/checkout@v4
      # - name: Install dependencies
      #   run: composer self-update && composer install && composer dump-autoload
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
      - name: Install dependencies
        run: |
          npm install
      - name: Install Composer
        run: |
          composer install
      - name: Run unit tests
        run: |
          npm run test:unit
      # - name: Run tests and collect coverage
      #   run: vendor/bin/phpunit --coverage-clover coverage.xml .
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v4-beta
      #   env:
      #     CODECOV_TOKEN: ${{ secrets.CODECOV_ORG_TOKEN }}
