name: Create Zip

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Zip files
        run: zip -r my-plugin.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-plugin
          path: my-plugin.zip
